### ISSUE TITLE
[FEATURE REQUEST] Overview pages for non-blog content

### ISSUE THREAD

**Issue by jzbor** [michaelneuper/hugo-texify3#3]
I have several different types of content on my website, and it would be nice to have an overview page for them.

This is my content layout:
```
.
├── homepage
│   └── about.md
├── posts
│   ├── test.md
├── projects
│   ├── lash.md
│   └── marswm.md
└── tut
    ├── _index.md
    └── sp2
        ├── _index.md
        ├── ue01.md
        ├── ue02.md
        └── ue03.md
```

With my current theme there are overview pages generated for `/projects` `/tut` and `/tut/sp2`:
![image](https://github.com/michaelneuper/hugo-texify3/assets/48366877/87fd54d2-18fd-4548-a3d9-3aaeb7136beb)
![image](https://github.com/michaelneuper/hugo-texify3/assets/48366877/16ea7b29-7702-48f5-9443-65fc9251bd86)
![image](https://github.com/michaelneuper/hugo-texify3/assets/48366877/f368a117-f038-45ef-ae00-ea53ba0e5fd3)

You can also [see for yourself](https://jzbor.de/projects).

However with Texify3 the overview pages are empty and therefore not really navigateable:
![image](https://github.com/michaelneuper/hugo-texify3/assets/48366877/2f8f5cfd-686f-4568-b2ab-009594ec515e)

It would be great if there were a template to cover those overview pages (I think in hugo they are called "list pages" or something).

Thanks for your efforts!

**Comment by michaelneuper** [comment]
The subdirectories in the `/content/` directory are called [sections](https://gohugo.io/content-management/sections/).
You can create pages for your sections by adding a layout for each section.

For example, to create a page for your "projects" section:
1. Create a file `/layouts/projects/list.html`
2. You can copy the contents of `layouts/_default/list.html` from this repo to that file
3. In line 37, change "pages" to "projects"
